# Generated by cucumber-sinatra. (2012-09-17 20:24:35 -0500)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/chessmaster.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = CHESSMASTER

class MyAppWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  MyAppWorld.new
end

Capybara.default_driver = :selenium

